export const data = [
  {
    id: 18764,
    name: 'Daniel',
    lastname: 'Bechara',
    age: '24',
    sport: 'Futebol',
    school: 'Unileste',
  },
  {
    id: 26245,
    name: 'Gabriel',
    lastname: 'Stulpen',
    age: '23',
    sport: 'Corrida',
    school: 'Unileste',
  },
  {
    id: 39785,
    name: 'Fernanda',
    lastname: 'Assis',
    age: '24',
    sport: 'Handbol',
    school: 'Unileste',
  },
  {
    id: 46542,
    name: 'Beatriz',
    lastname: 'Fernandes',
    age: '24',
    sport: 'Volei',
    school: 'Unileste',
  },
  {
    id: 59879,
    name: 'Evandro',
    lastname: 'Souza',
    age: '28',
    sport: 'Truco',
    school: 'Unileste',
  },
  {
    id: 76556,
    name: 'Luiz',
    lastname: 'Lana',
    age: '24',
    sport: 'Xadrez',
    school: 'Unileste',
  },
  {
    id: 54357,
    name: 'Israel',
    lastname: 'Morais',
    age: '25',
    sport: 'Volei',
    school: 'Unileste',
  },
  {
    id: 12345,
    name: 'Carolina',
    lastname: 'Silva',
    age: '22',
    sport: 'Natação',
    school: 'Unileste',
  },

  {
    id: 67890,
    name: 'Rafael',
    lastname: 'Oliveira',
    age: '27',
    sport: 'Basquete',
    school: 'Unileste',
  },

  {
    id: 23456,
    name: 'Mariana',
    lastname: 'Santos',
    age: '23',
    sport: 'Tênis',
    school: 'Unileste',
  },

  {
    id: 78901,
    name: 'Gustavo',
    lastname: 'Pereira',
    age: '25',
    sport: 'Futebol',
    school: 'Unileste',
  },

  {
    id: 34567,
    name: 'Amanda',
    lastname: 'Costa',
    age: '22',
    sport: 'Handbol',
    school: 'Unileste',
  },

  {
    id: 89012,
    name: 'Ricardo',
    lastname: 'Melo',
    age: '27',
    sport: 'Xadrez',
    school: 'Unileste',
  },

  {
    id: 45678,
    name: 'Larissa',
    lastname: 'Almeida',
    age: '24',
    sport: 'Volei',
    school: 'Unileste',
  },

  {
    id: 90123,
    name: 'Felipe',
    lastname: 'Santana',
    age: '26',
    sport: 'Futebol',
    school: 'Unileste',
  },
];
